language: java

before_install: ./mvnw initialize
install: ./mvnw verify -DskipTests=true -Dmaven.javadoc.skip=true
script:
  - ./mvnw test sonar:sonar -Dmaven.javadoc.skip=true -B

cache:
  directories:
    - $HOME/.m2
    - node
    - node_modules
    - $HOME/.sonar
before_cache:
  - rm -rf $HOME/.m2/repository/de/adesso

addons:
  sonarcloud:
    organization: "adessoag-github"
