language: java
before_install: ./mvnw initialize
cache:
  directories:
  - $HOME/.m2
  - node
  - node_modules

addons:
  sonarcloud:
    organization: "adessoag-github"
    branches:
      - master
      - develop
script:
  - ./mvnw install sonar:sonar
