language: java

before_install: ./mvnw initialize
script:
  - ./mvnw test sonar:sonar -B

cache:
  directories:
    - $HOME/.m2
    - node
    - node_modules
    - $HOME/.sonar

addons:
  sonarcloud:
    organization: "adessoag-github"
    branches:
      - master
      - develop
